targets = [{ triple = "x86_64-unknown-linux-gnu" }]

[licenses]
copyleft = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "ISC",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
]

[licenses.private]
ignore = true

[bans]
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
