[package]
name = "lib203"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
futures = "0.3.28"
gradescope-api = { path = "../gradescope-api" }
itertools = "0.11.0"
serde = { version = "1.0.180", features = ["derive"] }
